# Liquibase Properties - locla dev test
# PostgreSQL Connection for fyp scrum

url=jdbc:postgresql://172.26.193.91:1337/postgresdb
username=postgresdb
password=postgresdb
changeLogFile=change.yaml
driver=org.postgresql.Driver
